blank_issues_enabled: false
contact_links:
  - name: 1 💬 Discord Support
    url: https://discord.gg/your-invite-link
    about: Please ask support questions in our Discord server. Issues are for bugs and feature requests only.